### ISSUE TITLE
jQuery forEach error in console

### ISSUE THREAD

**Issue by daredev** [REJack/TS3WI-AdminLTE#1]
I'm getting JS error in Chrome.

    Uncaught TypeError: Cannot read property 'forEach' of null
    at HTMLDocument.<anonymous> (adminlte-remember.js:15)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)

I think solution for that would be to change 

    boxstates.forEach(function(box) {
        if (box.state == 0)
            $('.box[data-name="'+box.boxname+'"]').addClass('collapsed-box').find('.btn-box-tool[data-widget="collapse"] i').removeClass('fa-minus').addClass('fa-plus');
        else if (box.state == 1)
            $('.box[data-name="'+box.boxname+'"]').removeClass('collapsed-box').find('.btn-box-tool[data-widget="collapse"] i').removeClass('fa-plus').addClass('fa-minus');
    });

to 

    boxstates.each(function(box) {
        if (box.state == 0)
            $('.box[data-name="'+box.boxname+'"]').addClass('collapsed-box').find('.btn-box-tool[data-widget="collapse"] i').removeClass('fa-minus').addClass('fa-plus');
        else if (box.state == 1)
            $('.box[data-name="'+box.boxname+'"]').removeClass('collapsed-box').find('.btn-box-tool[data-widget="collapse"] i').removeClass('fa-plus').addClass('fa-minus');
    });

**Comment by REJack** [comment]
Thanks for reporting this issue, I'll check this later.
