### ISSUE TITLE
Icons Wont be Displayed Right

### ISSUE THREAD

**Issue by axiades** [REJack/TS3WI-AdminLTE#4]
![unbenannt](https://user-images.githubusercontent.com/19848667/38640382-643ac5ea-3dd4-11e8-8ee7-30b97feb0771.PNG)

There is a Problem.

See Image,

The Webserver is Hosted By All-Inkl.com
With PHP7.2

**Comment by REJack** [comment]
Yup, it seems that the grunt-process damages the font files. I'll change the grunt file to a simple .sh file.

As workaroud you can download the master and upload the font files from it.

**Comment by REJack** [comment]
I've fixed it😄 check out the latest release (Build50)
